### PR TITLE
fix CPPIGetOwner returning nil for world-owned entities

### PR DESCRIPTION
**Pull request by Bonyoze**

### CODE REVIEW

**Comment by Bonyoze** [comment]
~~NULL entities cant use :IsWorld() method, that will cause an error.~~

**Comment by Bonyoze** [comment]
Probably better to just check `ownerEnt ~= NULL` as that satisfies both player and world.
:GetNWEntity() always returns a null entity by default

**Comment by anormaltwig** [comment]
What are you talking about, E:IsWorld() exists on every entity.

**Comment by anormaltwig** [comment]
Screenshot_20230402-091314_Termux_1

**Comment by Bonyoze** [comment]
Garry put Chinese propaganda on my test server

I didn't bother to get up and check since every other method gives you the "Tried to use NULL entity" error

**Pull request merged**
