### PR TITLE
NW2 system; Unique NW2 vars; Allow perms if ownerless

### PR DESCRIPTION
**Pull request by Bonyoze**

### CODE REVIEW

**Comment by ANormalTwig** [comment]
I am not switching this to use NW2

**Review by anormaltwig — CHANGES_REQUESTED** [review]
Switch back to the normal NW functions

**Comment by Bonyoze** [comment]
> Switch back to the normal NW functions

It is better than SetNW* which networks the value every 10 seconds and not only once. I don't think an entity even exists clientside if it isn't in their PVS

**Comment by anormaltwig** [comment]
image

**Comment by Bonyoze** [comment]
Then use net.Send instead of the NWVar systems.

**Pull request closed without merging**
